export module compiler.ir.Error;

import <cstdint>;

namespace compiler::ir {
  export enum class Error : uint8_t {
    // Lexical errors
    EscapeSequenceUnexpectedEndOfInput,
    EscapeSequenceExpectedClosingBrace,
    EscapeSequenceExpectedTwoHexDigits,
    EscapeSequenceExpectedFourHexDigits,
    EscapeSequenceExpectedOneOrMoreHexDigits,
    EscapeSequenceExpectedSixOrFewerHexDigits,
    EscapeSequenceUnexpectedEnd,
    EscapeSequenceExpectedAfterBackslash,
    EscapeInvalidPercentEncoding,
    CharacterLiteralExpectedContent,
    CharacterLiteralExpectedEscapeAfterBackslash,
    CharacterLiteralExpectedClosingSingleQuote,
    CharacterLiteralUnexpectedLineBreak,
    StringLiteralExpectedClosingDoubleQuote,
    SpecifierLiteralExpectedClosingDoubleQuote,
    StringLiteralUnexpectedLineBreak,
    StringLiteralExpectedEscapeAfterBackslash,
    TemplateStringLiteralExpectedExpression,
    TemplateStringLiteralExpectedClosingBrace,
    TemplateStringLiteralExpectedClosingBacktick,
    UnaryPrefixOperatorExpectedValue,
    BinaryOperatorExpectedLHS,
    MultiLineCommentExpectedClosingAsteriskSlash,
    ArrowFunctionExpectedExpression,
    SpecifierExpectedPathAfterScheme,
    SpecifierExpectedHostAfterAuthority,
    ConditionExpectedExpression,
    ConditionExpectedClosingParenthesis,
    BlockExpectedClosingCurlyBrace,
    SelectorOperatorExpectedSelector,
    UnaryPrefixOperatorExpectedSelector,

    // Unicode errors
    UnicodeCodePointOutOfRange,
    UnicodeCodePointInvalid,
    UnicodeSurrogateCodePointIsNotAValidScalarValue,

    // Declaration/statement lexer errors
    DeclarationExplicitTypeCannotBeUsedWithPostfixUnaryOperators,
    DeclarationExpectedTypeExpressionAfterColon,
    DeclarationExpectedExpressionAfterAssignmentOperator,
    DeclarationCannotSkipAssignmentOperatorWithPostfixUnaryOperators,
    DeclarationStatementExpectedIdentifier,
    DeclarationStatementExpectedTypeExpressionAfterColon,
    DeclarationStatementExpectedInitializerExpressionAfterEquals,
    DeclarationStatementExpectedSemicolon,
    DeclarationExpectedIdentifier,
    DeclarationExpectedInitializerExpressionAfterEquals,
    EnumExpectedExpression,
    EnumExpectedClosingAngleBracket,
    ArrayExpectedExpression,
    ArrayExpectedClosingBracket,
    TupleExpectedExpression,
    TupleExpectedClosingParenthesis,
    ObjectExpectedDeclaration,
    ObjectExpectedClosingCurlyBrace,
    ImportExpectedIdentifier,
    ImportExpectedFromKeyword,
    ImportExpectedSpecifier,
    ImportExpectedIdentifierAfterIn,
    ImportExpectedSemicolon,
    RegisterExpectedIdentifier,
    RegisterExpectedFromKeyword,
    RegisterExpectedSpecifier,
    RegisterExpectedIdentifierAfterWith,
    RegisterExpectedSemicolon,
    DoExpectedScopeBlock,
    WhileExpectedCondition,
    WhileExpectedScopeBlock,
    IfExpectedCondition,
    IfExpectedScopeBlock,
    IfPatternExpectedCondition,
    IfPatternExpectedScopeBlock,
    ElseStatementExpectedScopeBlock,
    IfStatementExpectedCondition,
    IfStatementExpectedScopeBlockOrPatternArms,
    BreakStatementExpectedSemicolon,
    ContinueStatementExpectedSemicolon,
    ReturnStatementExpectedSemicolon,
    YieldStatementExpectedSemicolon,
    UnaryPrefixOperatorExpectedExpression,
    BinaryOperatorExpectedExpression,
    RepeatExpectedScopeBlock,
    RepeatExpectedWhileCondition,
    ForExpectedConditionOpen,
    ForExpectedBinding,
    ForExpectedInKeyword,
    ForExpectedExpression,
    ForExpectedConditionClose,
    ForExpectedScopeBlock,

    // Parser errors
    ParserExpectedObjectDeclaration,
    ParserBreakOutsideLoop,
    ParserContinueOutsideLoop,
    ParserExpectedWhenArmBody,
    ParserDuplicateDefaultInWhen,
    ParserExpectedWhenArm,
    ParserExpectedHexStart,
    ParserExpectedOctalStart,
    ParserExpectedBinaryStart,
    ParserExpectedDecimal,
  };
};